### ISSUE TITLE
Registered version is currently broken 

### ISSUE THREAD

**Issue by zenna** [tpapp/DynamicHMC.jl#52]
Registered version is currently broken because it uses latest LogDensityProblems   which gets rid of ValueGradient

[bbc10e6e] DynamicHMC v1.0.5

**Comment by tpapp** [comment]
Thanks for reporting this, this is a duplicate of #51. I released the fix yesterday, and hope it will trickle through the registry soon:

https://github.com/JuliaRegistries/General/pull/2317

In the meantime, I will leave this open.

**Comment by tpapp** [comment]
(Hopefully) fixed now as the above PR is merged.

**Comment by goedman** [comment]
Tamas, I installed v"1.0.6" of DynamicHMC and (I thought) the corresponding LogDensityProblems v"0.9.0" but still see in DynamicHMC.jl:
```
using LogDensityProblems: dimension, logdensity, ValueGradient, logdensity
```
I'd expected the last 2 items to be replaced by `logdensity_and_gradient` (which I have been playing around with the last few days).

But somehow Project.toml shows:
```
name = "DynamicHMC"
uuid = "bbc10e6e-7c05-544b-b16e-64fede858acb"
authors = ["Tamas K. Papp <tkpapp@gmail.com>"]
version = "1.0.6"

...

[compat]
julia = "1"
LogDensityProblems = "^0.8.0"
```

I'm clearly confused. I did reinstall all of .julia, but that did not help. DynamicHMC v"1.0.6" does work with LogDensityProblems v"0.8.3". Just wondering if somehow DynamicHMC v"1.0.6" is not the proper version for LogDensityProblems v"0.9.0".

**Comment by tpapp** [comment]
They are incompatible versions, you were not supposed to be able to install them at the same time. How did you do that?

There is currently no *released* version of DynamicHMC compatible with LogDensityProblems v0.9.0, the latter is used by `master`.

**Comment by goedman** [comment]
Thank you. Clearly my assumption was incorrect. I never had them installed at the same time but in different projects.

In chapter 9 of StatisticalRethinking McElreath provides a nice intro to HMC (and the NUTS variant) and I decided to include that snippet based on LogDensityProblems and updated that this weekend to the LogDensityProblems v"0.9.0" API. That's when I ran into this issue.
